In [1]:
import torch


In [26]:
w = torch.rand((1, 5))
w.requires_grad = True
x = torch.rand((5, 3))
x.requires_grad = True
y = torch.matmul(w, x)
print(y)
y_hat = y[:, [0, 2]]
print(y_hat)
ending = y_hat.sum()
ending.backward()
print(x.grad)
current_node = ending
while True:
    if hasattr(current_node, "grad_fn") :
        print(current_node.grad_fn)
        current_node = current_node.grad_fn.next_functions[0][0]
    elif hasattr(current_node, "next_functions") :
        print(current_node.next_functions)
        current_node = current_node.next_functions[0][0]
    else:
        break
    


tensor([[0.7533, 1.2392, 0.4888]], grad_fn=<MmBackward0>)
tensor([[0.7533, 0.4888]], grad_fn=<IndexBackward0>)
tensor([[0.3435, 0.0000, 0.3435],
        [0.0129, 0.0000, 0.0129],
        [0.2905, 0.0000, 0.2905],
        [0.6281, 0.0000, 0.6281],
        [0.5121, 0.0000, 0.5121]])
((<SliceBackward0 object at 0x00000232775E2050>, 0),)
((<MmBackward0 object at 0x00000232775E3D00>, 0),)
((<AccumulateGrad object at 0x00000232775E2050>, 0), (<AccumulateGrad object at 0x00000232775E4730>, 0))
()


IndexError: tuple index out of range